### PR TITLE
Jimmys Branch

### PR DESCRIPTION
**Pull request by Jimmy-John**
Recommitting previous commit due to indentation issues

### CODE REVIEW

**Comment by grahamgilbert** [comment]
I'm still not convinced by the use case. Crypt wasn't designed to be a reporting tool, it's an escrow tool. Why would you use this over MunkiReport, Sal etc?

**Comment by Jimmy-John** [comment]
Hey Graham,

Thanks for the quick response on this. The reason we are seeking reporting
through the Crypt application is indeed kind of an odd situation.  I work
for the University of Texas at Dallas (I actually sent you an e-mail
earlier, I'm Jeff, howdy =).  The issue is that our administration has
mandated that all machines in our environment be encrypted.  We previously
leaned on a commercial product called SecureDoc (by WinMagic) to handle our
full disk encryption.  However, SecureDoc currently does not currently
support Yosemite, and also does not support the latest version of Mavericks
(yay commercial products).

Anyways, we are trying to keep the number of agents we push out to the
campus at a minimum.  It would be a big win for us if we can cover
encryption and reporting with a single client.  We do have a desire to have
a CM tool cover the Mac portion of our infrastructure, but we don't have
the resources to properly implement that within the time frame that
encryption is required.  Plus the single client will be more adaptable by
the Campus, especially since it's only goal is to perform encryption.  I
can't really go into details, but we've had some of the more radical end
users have issues with CM tools before for privacy reasons.  At the end of
the day, having a more light weight tool is a better fit right now then
trying to move towards a more CM'ed infrastructure, though we do want to
get to there at some point.

My goal with the changes proposed was to give the client the ability to
check in without creating new keys for every checkin.  The changes to the
server leave all the previous functionality in place, while allowing the
client to specify a second "secret_type" for alternate functionality.  When
"checkin" is specified, the only work performed by the server is that the
computer object gets it's "last_checkin" property updated to the current
time, but only if the computer object is a previously registered object.
This seemed like a good place to store this data, as the last actual
recovery key checkin time is still easily referenced by looking at the keys
associated with the computer object, and seeing which one was last
created.  To me, it seemed the last_checkin held redundant data, so that
seemed to be the best place to hold onto this new date/time data without
modifying the current computer model.

I've tested the new server code with the current master client code, and it
seems to work fine.  I have yet to test the current server master code with
the new client, but it seems like everything should work just fine, and the
new checks will create "checkin" type secrets in the computer view.  I can
see how there could start to be a lot of these, so it probably be
preferable to add a preference option to enable the new checkins, which
would be turned off by default.  I could add that in and get it turned
around pretty quick.  I will also see about testing the new client with the
current server master as soon as I hit send on this.

All that being said, I can definitely see how this kind of encroaches
outside the scope of the original project.  My heart won't be to broken if
you turn down my code (I'll commiserate with a pint later today =).
However, there are still some fixes that I'd like to contribute to.  For
instance, I'm not sure why but it appears the the secrets of each computer
object get dumped to /var/log/apache2/error.log whenever a computer object
is viewed in the web console.  I'm betting it has something to do with the
secrets split again, but I'd like to track that down and get it fixed.
Also, I'm thinking about adding some input sanitizing to both the server
and the client that you might be interested in picking up.  In any event,
let me know.  If there are specific issues with the PR that make you a
little uneasy that I can correct, let me know, I like to think I'm pretty
flexible.

And if I haven't said ti before, many thanks for releasing this and giving
us a great tool that we can build on to meet our specific needs.

Much obliged,

Jimmy (or Jeff ... apparently the security community doesn't think you're
cool unless you use a screen name ... but I've never quite taken to it)

**Comment by arubdesu** [comment]
Coming in cold, but where's the proposal? Without knowing the features I'm going to be on the 'one thing well' side of this argument. I see no reason to add inventory, this isn't even a two-way server - things get sent so they're locked away, and this gets accessed rarely if ever

**Comment by Jimmy-John** [comment]
Howdy, and I appreciate the feedback.  The only feature that I'd like to see added to the current product is the ability for clients to report a checkin that they are still encrypted.  It seemed relevant enough to the current solution, as I'd be willing to bet that other folks out there are looking for an escrow solution that does checkin without the need to have a fully configuration managed solution.  However, I am usually on the "one thing well" side of the house, so I can definitely understand how this would not be desirable but what is probably a large portion of the user base.  I can keep this change to a personal deployment branch if that would work better for the current users of Crypt.

**Comment by grahamgilbert** [comment]
Thinking about it, I'm fine with the change, but I think it should be implemented differently. An escrow isn't a checkin. This would be a different mechanism that runs in the background via launchd that runs periodically. How to lay it out on the server needs to be thought about - maybe a verified date attribute on the secret (but then how do we know which secret we're verifying).

**Comment by arubdesu** [comment]
CM tools, even simple ones like the hooks themselves(managed or unmanaged), keep the client encrypted, and any mgmt tool can be extended to report - if you have munki then Sal or MR-PHP or anything else can be as simple as a postflight script. CryptClient isn't really an agent in and of itself, and any addition to functionality that needs testing and interacting with for reporting is overhead that's unnecessary to the common case. Vote against, but I totally respect the request and wish it was easier for you to maintain your fork, but it's my belief Crypt should stay relatively static.
(Says the guy who voted for arbitrary secrets server-side, and still needs to work on breaking out a firmware password table.)

**Comment by Jimmy-John** [comment]
I don't believe our use case calls for verification of the secret, really it's just to verify the computer itself is encrypted.  In the instance of a lost laptop, a report saying that it checked in 3 days ago with any secret is the real goal, aside from trying to ensure that a particular secret is still valid.  However, if you wanted to verify the secret, a secure salted hash of the key could be stored somewhere on the machine (perhaps /private/var/root), and that value could be sent with the checkin to verify that the secret is still current.

If this is something that would add value to Crypt, then I'd definitely be open to the idea that implementation considerations should be discussed at slightly greater detail then via the pull request.  So feel free to deny this one, I'll revert my branch, and I'll go about this in a more planned manner with additional input on the implementation.  If this is pushing the Crypt server/client architecture beyond its intentions, I'll still be happy to keep a copy of the current prod branch in case I bump into any fixes / improvements that are a little loser to home.

Yeah it may not be fun to maintain alternate branches, but I really need to start getting my hands dirty with more of the rote and routine work of development.  So, at the very least I'll be soakin' up that awesome experience =).

**Comment by Jimmy-John** [comment]
The more I look at this, the more it seems like a hack then an actual feature implementation.  I'm going to roll this back, and try to implement checkin functionality in another manner.  For starters, I'm going to create a separate URL so that I do not have to slip the condition for a checkin vs an escrow into secret_type.  Additionally, I'm thinking up creating a separate binary to perform the checkin.  This way checkin is further separated from the Crypt client, and I'm going to include a preference check which disables it by default.  I'd like to continue the discussion of adding "checkin" vs "escrow" functionality, but I'd also like to do so with better code.

**Pull request closed without merging**
