### PR TITLE
boot script

### PR DESCRIPTION
**Pull request by erikng**
First stab at boot script. We will need to add some logic to the Checkin as well, but I figure this is first.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
I'm wondering whether this should be stored somewhere else other than the plist with the key in? Then it's not overwritten when we add in automated rotation. Maybe just throw it in the prefs?

**Comment by erikng** [comment]
Only problem with the Preferences file is we don't know how people are managing it. Seems like a weird place to put it. Maybe just a separate plist?

**Comment by grahamgilbert** [comment]
It doesn't really matter - the script will still write to /Library/Preferences. Think of the last check value that Munki sets.

**Comment by grahamgilbert** [comment]
Bump

**Comment by erikng** [comment]
Sorry. Need to catch up on this. I'm going to try work on the ohai stuff first.

**Comment by weswhet** [comment]
Running at load resolves this.

**Pull request closed without merging**
