### PR TITLE
Document curl post for checkin script

### PR DESCRIPTION
**Pull request by erikng**
I opted to use the full variables and documented them so others can understand what options are being passed if they need to debug an issue.

### CODE REVIEW

**Comment by grahamgilbert** [comment]
This reintroduces the vulnerability fixed in https://github.com/grahamgilbert/crypt/issues/87

**Comment by grahamgilbert** [comment]
@erikng We can't merge this, as it reintroduces the vulnerability. What is the issue you are having with the current method and why does this fix it? We really need it to use the current method.

**Comment by erikng** [comment]
Ah okay this makes sense. To be honest I was just trying to document what the curl command itself does. What I can do is get the best of both worlds and make it more explicit while protecting the key from memory reads.

**Comment by erikng** [comment]
Updated the diff and tested.

**Comment by weswhet** [comment]
@erikng are you done making changes? LGTM so far.

**Comment by erikng** [comment]
Yep. I'm done.

**Review by weswhet — APPROVED** [review]
Thanks

**Pull request merged**
