### PR TITLE
Fixed Unified Logging so it write's logs from memory to data store before reboot. And minor logging improvements

### PR DESCRIPTION
**Pull request by weswhet**
Apologies on the multiple commits 

- So this fixes the issue of logs no appearing after an enablement reboot and then running the following command to view them.
```
sudo log show --predicate 'subsystem == "com.grahamgilbert.crypt"' --style syslog --last 3h --debug
```

This was done by changing from using `/sbin/reboot` to `/sbin/shutdown -r now` and setting the log level type to either default or error.

- More logging on other mechanisms.
- General Code readability and less calls to fdesetup on Check. The first check now returns a Tuple of info not just a Boolean. 
- Make File now uses the CFBundleShortVersionString for setting the pkg version number.
- Package preinstall now removes old Crypt.Bundle to fix some upgrading bugs that were noticed.

Below are logs from tests on the different parts of the code changes.

Logs from logging in as a Skipped User...
```
2017-08-10 10:22:44.072583-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:22:44.072743-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] Starting run of Crypt.Check...
2017-08-10 10:22:44.074835-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] Checking for any SkipUsers...
2017-08-10 10:22:44.074839-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:22:44.095567-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] Trimming admin to admin
2017-08-10 10:22:44.095664-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] Found admin in SkipUsers list...
2017-08-10 10:22:44.095705-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:22:44.095743-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting password...
2017-08-10 10:22:44.096559-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] Checking the current status of FileVault..
2017-08-10 10:22:44.155773-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] FileVault is not enabled...
2017-08-10 10:22:44.155843-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Check] Logged in User is in the Skip List... Not enforcing FileVault...
2017-08-10 10:22:44.156407-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called setBoolHintValue
2017-08-10 10:22:44.156629-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] called allowLogin
2017-08-10 10:22:44.174792-0700  localhost SecurityAgent[849]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:22:44.174811-0700  localhost SecurityAgent[849]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:22:44.178816-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:22:44.178858-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:22:44.179024-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.Enablement] Hint Value not set Allowing Login...
2017-08-10 10:22:44.179027-0700  localhost authorizationhost[1496]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] called allowLogin
```

Logs from initial enablement...

```
2017-08-10 10:26:47.922302-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:26:47.922330-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Check] Starting run of Crypt.Check...
2017-08-10 10:26:47.923838-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Check] Checking for any SkipUsers...
2017-08-10 10:26:47.923842-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:26:47.924698-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Check] Trimming admin to admin
2017-08-10 10:26:47.924722-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:26:47.924748-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting password...
2017-08-10 10:26:47.924933-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Check] Checking the current status of FileVault..
2017-08-10 10:26:48.016888-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Check] FileVault is not enabled...
2017-08-10 10:26:48.016927-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Check] FileVault is not enabled, Setting to enable...
2017-08-10 10:26:48.016955-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called setBoolHintValue
2017-08-10 10:26:48.040526-0700  localhost SecurityAgent[3491]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:26:48.040544-0700  localhost SecurityAgent[3491]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:26:49.630255-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:26:49.630365-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:26:49.630525-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] Attempting to enable FileVault
2017-08-10 10:26:49.630528-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:26:49.630553-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting password...
2017-08-10 10:26:49.698321-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] Authrestart capability is 'true', will authrestart as appropriate
2017-08-10 10:26:49.698329-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] Adding -authrestart to fdesetup arguments...
2017-08-10 10:26:49.698338-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] Checking for Institutional key...
2017-08-10 10:26:49.698353-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] Institutional key NOT found...
2017-08-10 10:27:20.513671-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] Trying to get output data
2017-08-10 10:27:20.520087-0700  localhost authorizationhost[3636]: (Crypt) [com.grahamgilbert.crypt.Enablement] called restartMac()...
```

Logs from checkin for initial Escrow and subsequent check...
```
2017-08-10 10:27:47 AM - INFO: Attempting to Escrow Key...
2017-08-10 10:27:47 AM - DEBUG: ServerURL Pref set to: REDACTED...
2017-08-10 10:27:47 AM - INFO: Key escrow successful.
2017-08-10 10:29:48 AM - INFO: OutputPath Pref is set to: /var/root/crypt-key.plist
2017-08-10 10:29:48 AM - INFO: Stored recovery key is valid.
2017-08-10 10:29:48 AM - INFO: KeyEscrowInterval set to: 1 hour(s)...
2017-08-10 10:29:48 AM - INFO: We escrowed less than 1 hour(s) ago. Skipping...
```
Logs from checkin after changing local key
```
2017-08-10 10:41:54 AM - INFO: OutputPath Pref is set to: /var/root/crypt-key.plist
2017-08-10 10:41:54 AM - INFO: Stored recovery key is not valid, removing from disk
```

Logs from logout in an attempt to rotate key
```
2017-08-10 10:43:43.887338-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:43:43.887375-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Starting run of Crypt.Check...
2017-08-10 10:43:43.889211-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Checking for any SkipUsers...
2017-08-10 10:43:43.889216-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:43:43.890200-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Trimming admin to admin
2017-08-10 10:43:43.890225-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting username...
2017-08-10 10:43:43.890252-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Requesting password...
2017-08-10 10:43:43.890484-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Checking the current status of FileVault..
2017-08-10 10:43:44.116993-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Filevault is On...
2017-08-10 10:43:44.117096-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] OutPutPlist Prefences is set to /var/root/crypt-key.plist
2017-08-10 10:43:44.117303-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] RotateUsedKey Prefences is set to true
2017-08-10 10:43:44.117332-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] RemovePlist Prefences is set to false
2017-08-10 10:43:44.117339-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Checking to see if /var/root/crypt-key.plist exists...
2017-08-10 10:43:44.117375-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] /var/root/crypt-key.plist doen NOT exists...
2017-08-10 10:43:44.117380-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Key is missing at /var/root/crypt-key.plist, and RemovePlist is False. And RotateKey is True, Attempting to generate a new key...
2017-08-10 10:43:44.117390-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Attempting to Rotate Recovery Key...
2017-08-10 10:43:44.907695-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Trying to get output data
2017-08-10 10:43:44.907834-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Attempting to write key to: /var/root/crypt-key.plist
2017-08-10 10:43:44.909535-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] Successfully wrote key to: /var/root/crypt-key.plist
2017-08-10 10:43:44.909641-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Check] All checks for an encypted machine have passed, Allowing Login...
2017-08-10 10:43:44.909654-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called setBoolHintValue
2017-08-10 10:43:44.909827-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] called allowLogin
2017-08-10 10:43:44.923704-0700  localhost SecurityAgent[3316]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:43:44.923738-0700  localhost SecurityAgent[3316]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:43:44.927596-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:43:44.927641-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:43:44.927767-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.Enablement] Hint Value not set Allowing Login...
2017-08-10 10:43:44.927769-0700  localhost authorizationhost[3334]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] called allowLogin
```

Logs during login while decrypting.

```
2017-08-10 10:51:57.277410-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.Check] Checking the current status of FileVault..
2017-08-10 10:51:57.763439-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.Check] FileVault Decryption in progress...
2017-08-10 10:51:57.763486-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.Check] We are Decrypting! Not much we can do, exiting for safety...
2017-08-10 10:51:57.764632-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called setBoolHintValue
2017-08-10 10:51:57.764924-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] called allowLogin
2017-08-10 10:51:57.785223-0700  localhost SecurityAgent[969]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:51:57.785264-0700  localhost SecurityAgent[969]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:51:57.792747-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] initWithMechanismRecord
2017-08-10 10:51:57.792819-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] Called getBoolHintValue
2017-08-10 10:51:57.793007-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.Enablement] Hint Value not set Allowing Login...
2017-08-10 10:51:57.793010-0700  localhost authorizationhost[1284]: (Crypt) [com.grahamgilbert.crypt.CryptMechanism] called allowLogin
```

### CODE REVIEW

**Review by grahamgilbert — CHANGES_REQUESTED** [review]
Can we split these out into separate PRs? I don't want to merge all you've done (notably removing the bundle in the preinstall - if the install fails, you'll break login)

**Comment by weswhet** [comment]
For sure, will do

**Comment by weswhet** [comment]
@grahamgilbert I removed the preinstall changes, anything else you wanted split out?

**Comment by weswhet** [comment]
@grahamgilbert ping 😃

**Review by grahamgilbert — APPROVED** [review]

**Pull request merged**
